#!/bin/bash
#
#
#
########################################################################################################################
#
# Escrito por: Allan R. A. Barcelos (Uberaba - Minas Gerais).
# E-mail: allanbarcelosmg@gmail.com
# Debian GNU/Linux 6.0.1
#
# NOME
#   mysql-remote-root-daemon.sh
#
# DESCRIÇÃO
#	Atualiza IP remoto para acesso ao MySQL utilizando usuário ROOT.
#
# VERSÃO
#	0.1
#
# NOTA
#	Informações sobre a execução poderão ser encontradas em  /var/log/mysql/mysql-remote-ip-root.log.
#
#
# MODIFICADO_POR	(DD/MM/YYYY)	Comentário
#
# allan.barcelos	01/06/2014	Primeira versão.
#
########################################################################################################################

LOCK=/tmp/mysql-remote-root-daemon.lock
LOG=/var/log/mysql/mysql-remote-ip-root.log
YES=/tmp/on
MYSQL=/usr/bin/mysql


URL_NOIP="SEU URL NOIP OU OUTRO SERVIÇO SEMELHANTE"
SENHA="SUA SENHA ROOT DO MYSQL"
DATETIME=$(/bin/date +"%d-%m-%Y %H:%M:%S")


#control_c () {
#        echo -e "\nacabou o daemon"
#        rm $YES 2>/dev/null
#        rm $LOCK 2>/dev/null
#        exit 0
#}
 
#trap control_c INT HUP TERM

echo "Iniciado o mysql-remote-root-daemon `date`" >> $LOG 2>/dev/null
 
if [ ! -f $LOCK ]
then
        touch $LOCK
 
        while true
        do
                sleep 30
                if [ -f $YES ]
                then
                        #echo "o arquivo $YES foi encontrado: `date`" >> $LOG
                        rm $YES 2>/dev/null
                        rm $LOCK 2>/dev/null
                        echo "Finalizado o mysql-remote-root-daemon `date`" >> $LOG 2>/dev/null
                        break
                fi



		
		/bin/ps -C mysqld > /dev/null #Verifica se o DAEMON MySQL esta ativo, caso contrario pode gerar erros.
		if [ $? = 0 ]
		then
			##
			IP=$(ping -w 1 -c 1 $URL_NOIP | grep PING | awk -F: '{print $1}' | awk -F "(" '{ print $2 }' | awk -F ")" '{ print $1}')
			IP_COUNT=$($MYSQL -B -u root -p$SENHA --disable-column-names -e "SELECT COUNT(*) FROM mysql.user WHERE User = 'root' AND Host = '$IP'" mysql)


			if [ $IP_COUNT == 0 ] ; then

				OLD_IP=$($MYSQL -B -u root -p$SENHA --disable-column-names -e "SELECT  Host FROM mysql.user WHERE User = 'root'\
				AND Host REGEXP '^(((1[0-9]|[1-9]?)[0-9]|2([0-4][0-9]|5[0-5]))\.){3}((1[0-9]|[1-9]?)[0-9]|2([0-4][0-9]|5[0-5]))$' AND Host NOT LIKE '127%'" mysql)

				if [ $OLD_IP != "" ] 2> /dev/null ; then

					$MYSQL -u root -p$SENHA -e "DROP USER 'root'@'$OLD_IP'";

				fi

				$MYSQL -u root -p$SENHA -e "CREATE USER 'root'@'$IP' IDENTIFIED BY '$SENHA'";
				$MYSQL -u root -p$SENHA -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'$IP' WITH GRANT OPTION";	
				echo "$DATETIME Novo IP Remoto ROOT MySQL $IP" >> $LOG 2>/dev/null

			fi
			##
		fi

		#echo "$DATETIME Sem alteracao"	>>  $LOG

        done
else
        echo "O mysql-remote-root-daemon já está em execução"
        exit 0
fi                                   
